import 'package:watime/model/location_model.dart';

class Location {
  static List<LocationModel> type = [
    const LocationModel(
      no: 0,
      code: "Pacific/Apia",
      continent: 0,
      location: "Apia",
    ),
    const LocationModel(
      no: 1,
      code: "Pacific/Midway",
      continent: 0,
      location: "Midway",
    ),
    const LocationModel(
      no: 2,
      code: "Pacific/Honolulu",
      continent: 0,
      location: "Honolulu",
    ),
    const LocationModel(
      no: 3,
      code: "America/Anchorage",
      continent: 3,
      location: "Anchorage",
    ),
    const LocationModel(
      no: 4,
      code: "America/Los_Angeles",
      continent: 3,
      location: "Los Angeles",
    ),
    const LocationModel(
      no: 5,
      code: "America/Santa_Isabel",
      continent: 3,
      location: "Santa Isabel",
    ),
    const LocationModel(
      no: 6,
      code: "America/Denver",
      continent: 3,
      location: "Denver",
    ),
    const LocationModel(
      no: 7,
      code: "America/Chihuahua",
      continent: 3,
      location: "Chihuahua",
    ),
    const LocationModel(
      no: 8,
      code: "America/Phoenix",
      continent: 3,
      location: "Phoenix",
    ),
    const LocationModel(
      no: 9,
      code: "America/Regina",
      continent: 3,
      location: "Regina",
    ),
    const LocationModel(
      no: 10,
      code: "America/Guatemala",
      continent: 3,
      location: "Guatemala",
    ),
    const LocationModel(
      no: 11,
      code: "America/Chicago",
      continent: 3,
      location: "Chicago",
    ),
    const LocationModel(
      no: 12,
      code: "America/New_York",
      continent: 3,
      location: "New York",
    ),
    const LocationModel(
      no: 13,
      code: "America/Bogota",
      continent: 3,
      location: "Bogota",
    ),
    const LocationModel(
      no: 14,
      code: "America/Caracas",
      continent: 3,
      location: "Caracas",
    ),
    const LocationModel(
      no: 15,
      code: "America/Halifax",
      continent: 3,
      location: "Halifax",
    ),
    const LocationModel(
      no: 16,
      code: "America/Cuiaba",
      continent: 3,
      location: "Cuiaba",
    ),
    const LocationModel(
      no: 17,
      code: "America/Santiago",
      continent: 3,
      location: "Santiago",
    ),
    const LocationModel(
      no: 18,
      code: "America/Asuncion",
      continent: 3,
      location: "Asuncion",
    ),
    const LocationModel(
      no: 19,
      code: "America/La_Paz",
      continent: 3,
      location: "La Paz",
    ),
    const LocationModel(
      no: 20,
      code: "America/St_Johns",
      continent: 3,
      location: "St Johns",
    ),
    const LocationModel(
      no: 21,
      code: "America/Bahia",
      continent: 3,
      location: "Bahia",
    ),
    const LocationModel(
      no: 22,
      code: "America/Sao_Paulo",
      continent: 3,
      location: "Sao Paulo",
    ),
    const LocationModel(
      no: 23,
      code: "America/Godthab",
      continent: 3,
      location: "Godthab",
    ),
    const LocationModel(
      no: 24,
      code: "America/Montevideo",
      continent: 3,
      location: "Montevideo",
    ),
    const LocationModel(
      no: 25,
      code: "America/Cayenne",
      continent: 3,
      location: "Cayenne",
    ),
    const LocationModel(
      no: 26,
      code: "America/Noronha",
      continent: 3,
      location: "Noronha",
    ),
    const LocationModel(
      no: 27,
      code: "Atlantic/Azores",
      continent: 1,
      location: "Azores",
    ),
    const LocationModel(
      no: 28,
      code: "Atlantic/Cape_Verde",
      continent: 1,
      location: "Cape Verde",
    ),
    const LocationModel(
      no: 29,
      code: "Europe/London",
      continent: 4,
      location: "London",
    ),
    const LocationModel(
      no: 30,
      code: "Atlantic/Reykjavik",
      continent: 1,
      location: "Reykjavik",
    ),
    const LocationModel(
      no: 31,
      code: "Africa/Casablanca",
      continent: 6,
      location: "Casablanca",
    ),
    const LocationModel(
      no: 32,
      code: "America/Danmarkshavn",
      continent: 3,
      location: "Danmarkshavn",
    ),
    const LocationModel(
      no: 33,
      code: "Europe/Budapest",
      continent: 4,
      location: "Budapest",
    ),
    const LocationModel(
      no: 34,
      code: "Europe/Warsaw",
      continent: 4,
      location: "Warsaw",
    ),
    const LocationModel(
      no: 35,
      code: "Africa/Windhoek",
      continent: 6,
      location: "Windhoek",
    ),
    const LocationModel(
      no: 36,
      code: "Europe/Paris",
      continent: 4,
      location: "Paris",
    ),
    const LocationModel(
      no: 37,
      code: "Africa/Lagos",
      continent: 6,
      location: "Lagos",
    ),
    const LocationModel(
      no: 38,
      code: "Europe/Berlin",
      continent: 4,
      location: "Berlin",
    ),
    const LocationModel(
      no: 39,
      code: "Africa/Cairo",
      continent: 6,
      location: "Cairo",
    ),
    const LocationModel(
      no: 40,
      code: "Europe/Bucharest",
      continent: 4,
      location: "Bucharest",
    ),
    const LocationModel(
      no: 41,
      code: "Asia/Jerusalem",
      continent: 5,
      location: "Jerusalem",
    ),
    const LocationModel(
      no: 42,
      code: "Africa/Tripoli",
      continent: 6,
      location: "Tripoli",
    ),
    const LocationModel(
      no: 43,
      code: "Asia/Beirut",
      continent: 5,
      location: "Beirut",
    ),
    const LocationModel(
      no: 44,
      code: "Africa/Johannesburg",
      continent: 6,
      location: "Johannesburg",
    ),
    const LocationModel(
      no: 45,
      code: "Asia/Damascus",
      continent: 5,
      location: "Damascus",
    ),
    const LocationModel(
      no: 46,
      code: "Europe/Istanbul",
      continent: 4,
      location: "Istanbul",
    ),
    const LocationModel(
      no: 47,
      code: "Asia/Riyadh",
      continent: 5,
      location: "Riyadh",
    ),
    const LocationModel(
      no: 48,
      code: "Asia/Baghdad",
      continent: 5,
      location: "Baghdad",
    ),
    const LocationModel(
      no: 49,
      code: "Europe/Minsk",
      continent: 4,
      location: "Minsk",
    ),
    const LocationModel(
      no: 50,
      code: "Africa/Nairobi",
      continent: 6,
      location: "Nairobi",
    ),
    const LocationModel(
      no: 51,
      code: "Asia/Amman",
      continent: 5,
      location: "Amman",
    ),
    const LocationModel(
      no: 52,
      code: "Europe/Kaliningrad",
      continent: 4,
      location: "Kaliningrad",
    ),
    const LocationModel(
      no: 53,
      code: "Asia/Tehran",
      continent: 5,
      location: "Tehran",
    ),
    const LocationModel(
      no: 54,
      code: "Asia/Baku",
      continent: 5,
      location: "Baku",
    ),
    const LocationModel(
      no: 55,
      code: "Asia/Yerevan",
      continent: 5,
      location: "Yerevan",
    ),
    const LocationModel(
      no: 56,
      code: "Asia/Tbilisi",
      continent: 5,
      location: "Tbilisi",
    ),
    const LocationModel(
      no: 57,
      code: "Indian/Mauritius",
      continent: 2,
      location: "Mauritius",
    ),
    const LocationModel(
      no: 58,
      code: "Europe/Samara",
      continent: 4,
      location: "Samara",
    ),
    const LocationModel(
      no: 59,
      code: "Europe/Moscow",
      continent: 4,
      location: "Moscow",
    ),
    const LocationModel(
      no: 60,
      code: "Asia/Kabul",
      continent: 5,
      location: "Kabul",
    ),
    const LocationModel(
      no: 61,
      code: "Asia/Karachi",
      continent: 5,
      location: "Karachi",
    ),
    const LocationModel(
      no: 62,
      code: "Asia/Tashkent",
      continent: 5,
      location: "Tashkent",
    ),
    const LocationModel(
      no: 63,
      code: "Asia/Colombo",
      continent: 5,
      location: "Colombo",
    ),
    const LocationModel(
      no: 64,
      code: "Asia/Kathmandu",
      continent: 5,
      location: "Kathmandu",
    ),
    const LocationModel(
      no: 65,
      code: "Asia/Dhaka",
      continent: 5,
      location: "Dhaka",
    ),
    const LocationModel(
      no: 66,
      code: "Asia/Almaty",
      continent: 5,
      location: "Almaty",
    ),
    const LocationModel(
      no: 67,
      code: "Asia/Yekaterinburg",
      continent: 5,
      location: "Yekaterinburg",
    ),
    const LocationModel(
      no: 68,
      code: "Asia/Rangoon",
      continent: 5,
      location: "Rangoon",
    ),
    const LocationModel(
      no: 69,
      code: "Asia/Bangkok",
      continent: 5,
      location: "Bangkok",
    ),
    const LocationModel(
      no: 70,
      code: "Asia/Novosibirsk",
      continent: 5,
      location: "Novosibirsk",
    ),
    const LocationModel(
      no: 71,
      code: "Asia/Shanghai",
      continent: 5,
      location: "Shanghai",
    ),
    const LocationModel(
      no: 72,
      code: "Asia/Krasnoyarsk",
      continent: 5,
      location: "Krasnoyarsk",
    ),
    const LocationModel(
      no: 73,
      code: "Asia/Singapore",
      continent: 5,
      location: "Singapore",
    ),
    const LocationModel(
      no: 74,
      code: "Asia/Taipei",
      continent: 5,
      location: "Taipei",
    ),
    const LocationModel(
      no: 75,
      code: "Asia/Ulaanbaatar",
      continent: 5,
      location: "Ulaanbaatar",
    ),
    const LocationModel(
      no: 76,
      code: "Australia/Perth",
      continent: 7,
      location: "Perth",
    ),
    const LocationModel(
      no: 77,
      code: "Asia/Seoul",
      continent: 5,
      location: "Seoul",
    ),
    const LocationModel(
      no: 78,
      code: "Asia/Irkutsk",
      continent: 5,
      location: "Irkutsk",
    ),
    const LocationModel(
      no: 79,
      code: "Asia/Tokyo",
      continent: 5,
      location: "Tokyo",
    ),
    const LocationModel(
      no: 80,
      code: "Australia/Darwin",
      continent: 7,
      location: "Darwin",
    ),
    const LocationModel(
      no: 81,
      code: "Australia/Adelaide",
      continent: 7,
      location: "Adelaide",
    ),
    const LocationModel(
      no: 82,
      code: "Australia/Sydney",
      continent: 7,
      location: "Sydney",
    ),
    const LocationModel(
      no: 83,
      code: "Australia/Brisbane",
      continent: 7,
      location: "Brisbane",
    ),
    const LocationModel(
      no: 84,
      code: "Australia/Hobart",
      continent: 7,
      location: "Hobart",
    ),
    const LocationModel(
      no: 85,
      code: "Asia/Yakutsk",
      continent: 5,
      location: "Yakutsk",
    ),
    const LocationModel(
      no: 86,
      code: "Pacific/Guadalcanal",
      continent: 0,
      location: "Guadalcanal",
    ),
    const LocationModel(
      no: 87,
      code: "Asia/Srednekolymsk",
      continent: 5,
      location: "Srednekolymsk",
    ),
    const LocationModel(
      no: 88,
      code: "Asia/Vladivostok",
      continent: 5,
      location: "Vladivostok",
    ),
    const LocationModel(
      no: 89,
      code: "Pacific/Fiji",
      continent: 0,
      location: "Fiji",
    ),
    const LocationModel(
      no: 90,
      code: "Asia/Magadan",
      continent: 5,
      location: "Magadan",
    ),
    const LocationModel(
      no: 91,
      code: "Pacific/Auckland",
      continent: 0,
      location: "Auckland",
    ),
    const LocationModel(
      no: 92,
      code: "Asia/Kamchatka",
      continent: 5,
      location: "Kamchatka",
    ),
    const LocationModel(
      no: 93,
      code: "Pacific/Tarawa",
      continent: 0,
      location: "Tarawa",
    ),
    const LocationModel(
      no: 94,
      code: "Pacific/Tongatapu",
      continent: 0,
      location: "Tongatapu",
    ),
    const LocationModel(
      no: 95,
      code: "Pacific/Kiritimati",
      continent: 0,
      location: "Kiritimati",
    ),
  ];
}
